//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Articles.Workflows.Hosting.SelfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SelfServiceReference.ServiceMainActivity")]
    public interface ServiceMainActivity {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ServiceMainActivity/Print")]
        void Print(Articles.Workflows.Hosting.SelfServiceReference.Print request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ServiceMainActivity/PrintExtended")]
        void PrintExtended(Articles.Workflows.Hosting.SelfServiceReference.PrintExtended request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceMainActivity/Read", ReplyAction="http://tempuri.org/ServiceMainActivity/ReadResponse")]
        Articles.Workflows.Hosting.SelfServiceReference.ReadResponse Read(Articles.Workflows.Hosting.SelfServiceReference.ReadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Print", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Print {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Message;
        
        public Print() {
        }
        
        public Print(string Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintExtended", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PrintExtended {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Message;
        
        public PrintExtended() {
        }
        
        public PrintExtended(string Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Message;
        
        public ReadRequest() {
        }
        
        public ReadRequest(string Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Line;
        
        public ReadResponse() {
        }
        
        public ReadResponse(string Line) {
            this.Line = Line;
        }
    }
}
