//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Articles.Workflow.Hosting.Client.WFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WFService.ServiceMainActivity")]
    public interface ServiceMainActivity {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ServiceMainActivity/Print")]
        void Print(string Message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ServiceMainActivity/PrintExtended")]
        void PrintExtended(string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceMainActivity/Read", ReplyAction="http://tempuri.org/ServiceMainActivity/ReadResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Line")]
        string Read(string Message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceMainActivityChannel : Articles.Workflow.Hosting.Client.WFService.ServiceMainActivity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMainActivityClient : System.ServiceModel.ClientBase<Articles.Workflow.Hosting.Client.WFService.ServiceMainActivity>, Articles.Workflow.Hosting.Client.WFService.ServiceMainActivity {
        
        public ServiceMainActivityClient() {
        }
        
        public ServiceMainActivityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMainActivityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMainActivityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMainActivityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Print(string Message) {
            base.Channel.Print(Message);
        }
        
        public void PrintExtended(string Message) {
            base.Channel.PrintExtended(Message);
        }
        
        public string Read(string Message) {
            return base.Channel.Read(Message);
        }
    }
}
